version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    command:  bash -c "gunicorn app:app -b 0.0.0.0:8000 && python3 manage.py createdb && python3 manage.py createsuperuser"
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
    - "80:80"
    depends_on:
      - app

  db:
    image: postgres:12
    networks:
      - default
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
