version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: python manage.py run -h 0.0.0.0 -p 8000
    volumes:
      - ./:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
    - "127.0.0.1:80:80"
    depends_on:
      - app

  db:
    image: postgres:12
    networks:
      - default
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
