# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Blog Flask

on:
  push:
    branches: [ master,feature-* ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  deploy:

    runs-on: ubuntu-latest
    needs: [ build ]
    if: ${{ success() && github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Digital Ocean
      env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SUPERUSER_PASS: ${{ secrets.SUPERUSER_PASS }}
      uses: wshihadeh/docker-deployment-action@v1
          with:
            remote_docker_host: root@161.35.75.206
            ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
            ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
            stack_file_name: docker-compose.server.yaml
            args: up -d